### ISSUE TITLE
HTML tags injected by other plugins are overwritten

### ISSUE THREAD

**Issue by develohpanda** [yzydeveloper/vite-plugin-multiple-page#3]
Hi there,

Thank you for this plugin! I've been trying to use it in conjunction with `vite-plugin-pwa`.

The PWA plugin injects HTML `script` and `link` tags similar to how this MPA plugin injects the JS and CSS entry points. You can see where the PWA plugin injects [here](https://github.com/antfu/vite-plugin-pwa/blob/9cd988cfc183eaa385216f36dcf3131f342b7b9d/src/plugins/build.ts#L22) and [here](https://github.com/antfu/vite-plugin-pwa/blob/main/src/html.ts).

The problem is that this MPA plugin (`vite-plugin-mpa-plus@0.5.0`) overwrites anything injected by another plugin, thus my output html files do not have the nodes injected by the PWA plugin. If I run the PWA plugin before the MPA plugin in `vite.config.ts`, I see the same behavior unfortunately.

This is a recent break. In `vite-plugin-multiple-page@0.4.3`, the contents injected by other plugins are _not_ overwritten and it works correctly, and on looking through your recent commits it could be a result of using `emitFile` or `writeBundle`?

**Comment by develohpanda** [comment]
@yzydeveloper I've narrowed this down to how the `emittedFiles` array is being used, this line in particular https://github.com/yzydeveloper/vite-plugin-mpa-plus/blob/5fd0049a0d0bf30ff74908e110e23a4783a74d61/packages/core/src/htmlFixPlugin.ts#L75

What's happening is that in the `transformIndexHtml` hook, we are putting the file contents to be written to `dist` into the `emittedFiles` array. This is an issue because between the time the `transformIndexHtml` hook runs in this plugin, and `closeBundle` runs to write the files, other plugins and their `transformIndexHtml` can also run. But because we put the file contents into `emittedfiles`, we effectively ignore any other calls.

To test this in my current solution I just made a few updates to this package in my `node_modules` folder, but I can try raise a PR within a day or so with a solution.

**Comment by yzydeveloper** [comment]
@develohpanda In the plugin, emitFile is performed in the writeBundle hook. I am trying to dist that will not affect the final output. Performing emitFile here will only make a prompt message for the asset, because it will not output the file.

**Comment by yzydeveloper** [comment]
@develohpanda About PR I strive to see today

**Comment by yzydeveloper** [comment]
@develohpanda I think I found the reason, because in the transformIndexHtml hook, I saved the original html content, and overwritten it with the saved html when I close theBundle
