### ISSUE TITLE
closeBundle() 中判断是否build的地方是否可以修改

### ISSUE THREAD

**Issue by dupingwei** [yzydeveloper/vite-plugin-multiple-page#5]
https://github.com/yzydeveloper/vite-plugin-mpa-plus/blob/f6ab085132be4eba1723a63754c34fdd48eb85b0/packages/core/src/htmlFixPlugin.ts#L98

### 建议修改为：
```
if (!isBuild(viteConfig.command)) return;

function isBuild(command: string) {
    return command === 'build';
}
```

### 原因：
项目可能会存在多种build:mode，如CDN、local、sandbox等等

### 参考：
```
export declare type ResolvedConfig = {
    ...
    command: 'build' | 'serve';
    mode: string;
    ...
}
```

**Comment by yzydeveloper** [comment]
刚又复查了一遍，我认为 closeBundle 属于 Output Generation Hooks ，是不是不需要对环境进行判断了？😂

**Comment by dupingwei** [comment]
以下钩子在服务器关闭时被调用：
[buildEnd](https://rollupjs.org/guide/en/#buildend)
[closeBundle](https://rollupjs.org/guide/en/#closebundle)

是的😂

**Comment by yzydeveloper** [comment]
老哥你可以提个PR。
